### ISSUE TITLE
Unable to update a single value without rewriting the entire keys to the file

### ISSUE THREAD

**Issue by fliptoback** [MarioZ/MadMilkman.Ini#28] opened 2019-04-10 15:33 UTC
Hi Mario,

I am having some issues to update a single key value in the ini file consisting of many other sections and keys

This is a shortened version of my code:
Dim INI As New IniFile
INI.Load("C:\temp\settings.ini")
Dim section As IniSection = INI.Sections.Add("Settings")
section.Keys.Add("ColorTheme", "4")
INI.Save("c:\temp\settings.ini")

if I run the above code, the colortheme setting will get written to the ini file but the rest of the original ini entries are all deleted.

How do I avoid this? I just want to update a nominated key value.

Thanks

**Comment by MarioZ** [comment] 2019-04-11 06:53
Can you send me your "settings.ini" file?  
Unfortunately, I was unable to reproduce this issue, here is what I have tried:

**settings-input.ini:**
```cfg
[SampleSection]
SampleKey1=1
SampleKey2=2
```

**Code:**
```vb.net
Dim INI As New IniFile
INI.Load("settings-input.ini")
Dim section As IniSection = INI.Sections.Add("Settings")
section.Keys.Add("ColorTheme", "4")
INI.Save("settings-output.ini")
```

**settings-output.ini:**
```cfg
[SampleSection]
SampleKey1=1
SampleKey2=2
[Settings]
ColorTheme=4
```

Is it possible that some other code is also overriding your "settings.ini" file?
The code that you provided should work as expected.

**Comment by fliptoback** [comment] 2019-04-11 10:34
Hi Mario, thanks for that.

My Settings.ini file as attached. I wonder if it is because of the way my
code works? I have defined different "sections" for each section of the ini
file. should I have done this or not?

                Dim section1 As IniSection = INI.Sections.Add("Settings")
                Dim keys As IniKey
                section1.Keys.Add("AutoMinimize",
AutoMinimizeCheckBox.Checked)
                section1.Keys.Add("ColorTheme",
ColorThemeListbox.SelectedIndex + 1)

                Dim section2 As IniSection = INI.Sections.Add("Winform")
                'Dim key As IniKey
                section2.Keys.Add("MainWindowsBackgroundColor",
Form1.Form1BackColor)
                section2.Keys.Add("MainWindowsForegroundColor",
Form1.Form1ForeColor)
                section2.Keys.Add("MainWindowsBorderColor", "")

                Dim section3 As IniSection = INI.Sections.Add("Panels")
                'Dim key As IniKey
                section3.Keys.Add("Panel1Title", Panel1TextBox.Text)
                section3.Keys.Add("Panel2Title", Panel2TextBox.Text)
                section3.Keys.Add("Panel3Title", Panel3TextBox.Text)
                section3.Keys.Add("Panel4Title", Panel4TextBox.Text)
                section3.Keys.Add("Panel1TextColor", Form1.Panel1TextColor)
                section3.Keys.Add("Panel2TextColor", Form1.Panel2TextColor)
                section3.Keys.Add("Panel3TextColor", Form1.Panel3TextColor)
                section3.Keys.Add("Panel4TextColor", Form1.Panel4TextColor)
                section3.Keys.Add("Panel1BackgroundColor",
Form1.Panel1BackColor)
                section3.Keys.Add("Panel2BackgroundColor",
Form1.Panel2BackColor)
                section3.Keys.Add("Panel3BackgroundColor",
Form1.Panel3BackColor)
                section3.Keys.Add("Panel4BackgroundColor",
Form1.Panel4BackColor)

                Dim section4 As IniSection = INI.Sections.Add("Buttons")
                section4.Keys.Add("ToolbarButtonBorder",
Me.ToolbarButtonBorderSizeNumericUpDown.Value)
                section4.Keys.Add("PanelButtonBorder",
Me.PanelButtonBorderSizeNumericUpDown.Value)
                section4.Keys.Add("SidebarButtonBorder",
Me.SidebarButtonBorderSizeNumericUpDown.Value)

Cheers
Joseph

**Comment by MarioZ** [comment] 2019-04-11 10:42
Unfortunately, you haven't sent any attachment.
Nevertheless, your code is ok, you can have multiple sections and each can have multiple keys.
I think your problem is with something else.

Can you send me a small VS project, a small solution that can reproduce your issue so that I can investigate it?

**Comment by fliptoback** [comment] 2019-04-11 13:01
Hi Mario,

Gmail just refuse to send the source code which I zipped so out of
desperation I have uploaded the code to my dropbox share folder.

https://www.dropbox.com/sh/iyb3d2w0jv49qtp/AAD4Qb_ez30KFalHwKGK3c36a?dl=0

Now that I have created a new project file, I am not sure what happen but
when i press the button to "write" to the ini file, it will kept appending
to the original file instead of writing from scratch. Again I am not sure
how to just update one key only.

Appreciate your thoughts.

Cheers

**Comment by MarioZ** [comment] 2019-04-11 13:40
Note "IniFile.Sections" and "IniSection.Keys" are collections and when you're using Add method on them they will append new item at the end.  
You should work with them in the same way how you would work with any collection, like for example with a List.  
So, you can use something like the following to check if some desired section and/or key exists, if it does then retreive it and if it doesn't then add it:
```vb.net
INI.Load(filename)

Dim section1 As IniSection = INI.Sections("Settings")
If section1 Is Nothing Then section1 = INI.Sections.Add("Settings")

Dim key1 As IniKey = section1.Keys("AutoMinimize")
If key1 Is Nothing Then
    key1 = section1.Keys.Add("AutoMinimize", True)
Else
    key1.Value = True
End If

Dim key2 As IniKey = section1.Keys("ColorTheme")
If key2 Is Nothing Then
    key2 = section1.Keys.Add("ColorTheme", 1)
Else
    key2.Value = 1
End If

' ...
```

I hope this helps.

**Comment by fliptoback** [comment] 2019-04-11 14:22
Hi Mario,

Yes! I think I understand this. I will try to change my coding tomorrow and will report back when things are working. Thanks again

**Comment by MarioZ** [comment] 2019-04-16 13:46
Hi,

I presume that the above example was of help to you and that you were able to resolve the issue, so I'll close this ticket.
But in case it's not or in case you have some other question, please let me know.

Regards,
Mario

**Closed as completed by MarioZ** 2019-04-16 13:46 UTC
Labels: question
